server:
  port: 9002
spring:
  application:
    name: microservice-rest-uppercase

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
