server:
  port: 9002

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekapeer0:8080/eureka,http://eurekapeer1:8081/eureka,http://eurekapeer2:8082/eureka

management:
  security:
    enable: false
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics

info:
  app:
    name: 'uppercase service'
    description: 'Simple uppercase service'
    version: ${version}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud: DEBUG
    com.netflix: DEBUG
    org.hibernate: DEBUG
    org.meng.cloud: DEBUG