server:
  port: 9002

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka

management:
  security:
    enable: false
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics

info:
  app:
    name: 'uppercase service'
    description: 'Simple uppercase service'
    version: '1.0'
