server:
  port: 9001
spring:
  application:
    name: microservice-rest-echo

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
