server:
  port: 8080
eureka:
  instance:
    hostname: eurekapeer0
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eurekapeer1:8081/eureka,http://eurekapeer2:8082/eureka