server:
  port: 8082
eureka:
  instance:
    hostname: eurekapeer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eurekapeer0:8080/eureka,http://eurekapeer1:8081/eureka